### ISSUE TITLE
Choosing a level will close app

### ISSUE THREAD

**Issue by iteachit** [WorldOfMogwais/WoMNetCore#1]
I was trying the different functions.
In the playing screen, click on level.  At the list screen, I choose a class and when I click on OK the app shutdown. 

![image](https://user-images.githubusercontent.com/40798317/45789193-60a89f00-bc4c-11e8-8e11-62bfddc0f974.png)

**Comment by darkfriend77** [comment]
okay. I will fix this ... check if it also happens when you clicked on your selectuin and it shows an asterix.

**Comment by darkfriend77** [comment]
https://github.com/WorldOfMogwais/WoMNetCore/releases/tag/v1.1.2

fixed
