### ISSUE TITLE
Suggestions: S is for Sending X mog to an address

### ISSUE THREAD

**Issue by iteachit** [WorldOfMogwais/WoMNetCore#10]
Suggestion:

Currently in it says that **S** is for sending 5 mog to address.  But since you have added the incr funds sent.. 5 is not the default anymore.  Ive just pressed **S**, thinking it was going to be 5..but was reassured when I asw the address just got 2. 

![image](https://user-images.githubusercontent.com/40798317/46048839-7d841d00-c0f9-11e8-8e07-3a983f098a07.png)

**Comment by darkfriend77** [comment]
thx, implemented in latest push.
