### ISSUE TITLE
BUG: Game keeps Crashing at class selection & sometimes randomly when key is pressed. 

### ISSUE THREAD

**Issue by iteachit** [WorldOfMogwais/WoMNetCore#4]
I first tried to use the class selection and the game crashes.  A buch of code dump happens on the other window that is open.  See animaged gif.

![1 1 2_levelup_crash](https://user-images.githubusercontent.com/40798317/45859510-b0f92d00-bd30-11e8-8869-3a8f47f3310c.gif)

**Comment by darkfriend77** [comment]
this bug should be fixed now ... 

https://github.com/WorldOfMogwais/WoMNetCore/releases/tag/v1.1.2
