### ISSUE TITLE
TYPO : There is a spelling mistake in MNEMOIC

### ISSUE THREAD

**Issue by iteachit** [WorldOfMogwais/WoMNetCore#6]
When the app create the restore keywords for you, the window title there is a spelling mistake there. 
It shows MNEMOIC when it should be MNEMO**N**IC.  See screenshot. 

![image](https://user-images.githubusercontent.com/40798317/45928452-f1fc6780-bf11-11e8-9adb-b1ecf76d615c.png)

**Comment by darkfriend77** [comment]
fixed
