### ISSUE TITLE
Suggestions: Hiding the background form (window)

### ISSUE THREAD

**Issue by iteachit** [WorldOfMogwais/WoMNetCore#8]
Just a thought..

Might want to hide the main exe window, while the users are playing the game.  Computer illiterate, might think there is a problem. 

![image](https://user-images.githubusercontent.com/40798317/46047807-845c6100-c0f4-11e8-9fe7-5b737a54c165.png)

**Comment by darkfriend77** [comment]
This is only a framework tool in the real game (unity3d)  on the mobile or on PC you will not have such a gui or window.
